({
    // This file was auto-generated by the build script

  // $Label.FinServWaveExt.Wave_Tab_Client_List
  // $Label.FinServWaveExt.Wave_Tab_8020
  // $Label.FinServWaveExt.Wave_Tab_Activities
  // $Label.FinServWaveExt.Wave_Tab_Financial_Accounts
  // $Label.FinServWaveExt.Wave_Tab_Client_Goals
})